---
title: "Netherlands Center for Computational Sociology"
output:
  html_document:
    toc: false
    number_sections: false
author: ""
bibliography: references.bib

---

```{r, install remotely, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
# install.packages("remotes")
#remotes::install_github("rlesur/klippy")
``` 

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

<br>

----

# Netherlands Center for Computational Sociology (NC2S)
Last compiled on `r format(Sys.time(), '%B, %Y')`  

Welcome to the Netherlands Center for Computational Sociology! We are a group of sociologists based at Dutch universities applying computational social science methods, (really) very broadly construed, to the study of inequality, culture, and social relationships. 

NC2S's goal is to promote computational sociology nationally and internationally -- as we believe the approach is a powerful analytical tool to ask answer novel sociological questions. To this end, we organize seminars to talk about and give feedback on one anothers' research papers, provide support to NC2S members in their research, exchange ideas and research practices in an open, team science way, and are constantly developing new ways to employ new methods and/or data at the forefront of (computational) sociological research.

On this website you'll find who we are, what we do, and some examples of our research, code vignettes, and an overview of (what we consider) courses in computational sociology at Dutch universities.

<br>

----







