---
title: "People"
#bibliography: references.bib
author: "Bas Hofstra"
---



```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>

----
  
# Who's who?

We are a relatively new center, yet we bundle decades of experience in the computational sociology approach and in publishing in sociological and interdisciplinary outlets about computational sociology.

## Bas Hofstra
Bas Hofstra is a tenured Assistant Professor at Radboud University's Department of Sociology. He got his PhD from Utrecht University's Department of Sociology and was Postdoctoral Research Fellow at Stanford University.

His work orbits the study of diversity, stratification, and innovation. It captures longitudinal systems of social and cultural exchange: from the gestation and birth of networks, careers, ideas, or innovations, to their use, up until their eventual cessation. As such, I strive for three interrelated goals: (i) answering substantive questions on causes and effects of social networks, while (ii) contributing to social theory, and (iii) using computational methods and big data. His research appeared (among others) in PNAS, American Sociological Review, Social Forces, Social Networks, and Nature Human Behaviour, and was honored with several grants and awards.



----





